### ISSUE TITLE
MIDI 2 CV Poly - an extra octaves range?

### ISSUE THREAD

**Issue by mxmilkb** [moddevices/mod-cv-plugins#19]
Might it be possible to get the option of an extra octave lower, i.e with an octave range that goes to -4?

**Comment by BramGiesen** [comment]
For our own version we will keep the -3 to +3 range. But if you would like to have a range from -4 to +4 you could change the ranges of the "Octave" parameter in the `mod-midi-to-cv-poly.ttl` like this: 
```
[
    a lv2:InputPort ,
    lv2:ControlPort ;
    lv2:index 10 ;
    lv2:symbol "Octave" ;
    lv2:name "Octave";
    lv2:default 0 ;
    lv2:minimum -4 ;
    lv2:maximum 4 ;
    lv2:portProperty lv2:integer;
],

```

**Comment by falkTX** [comment]
@BramGiesen I can suggest the following:
```
    lv2:minimum -4 ;
    lv2:maximum 4 ;
    mod:minimum -3 ;
    mod:maximum 3 ;
```
That way the "desktop" version of the plugin uses -4/+4, while the version for MOD uses -3/+3

**Comment by BramGiesen** [comment]
@falkTX, that's I good suggestion I can add that.
