### ISSUE TITLE
clock divider has multiple ranges in ttl

### ISSUE THREAD

**Issue by falkTX** [moddevices/mod-cv-plugins#23]
Specifically, stuff like this:
```
    lv2:minimum 0.0 ;
    lv2:maximum 10.0 ;
    lv2:symbol "ClockOut1";
    lv2:name "ClockOut1";
    lv2:minimum 0.0 ;
    lv2:maximum 2.0 ;
```

minimum and maximum are defined twice.
which one gets used is random in lilv.

I guess you meant to delete one of them and forgot?

**Comment by BramGiesen** [comment]
Yes, indeed. I removed them now, thanks.
