### ISSUE TITLE
What is the license for logic-operators.lv2?

### ISSUE THREAD

**Issue by SpotlightKid** [moddevices/mod-cv-plugins#28]
These state that the license is "Custom" but don't state what the license terms are:

https://github.com/moddevices/mod-cv-plugins/blob/85f9acdbe936f8fe3bd71f8a15fda01429a74ac4/source/mod-logic-operators/plugins/logic-operators/logic-operators.hpp#L60

https://github.com/moddevices/mod-cv-plugins/blob/85f9acdbe936f8fe3bd71f8a15fda01429a74ac4/source/mod-logic-operators/plugins/logic-operators/lv2-data/logic-operators_dsp.ttl#L100

Since the other plugins in this collection have "GPL v2+" as the license, should this be licensed like this as well?

**Comment by BramGiesen** [comment]
Yes, this should indeed be "GPL v2+". I've updated the plugin now with the correct license mentioned.
